### ISSUE TITLE
siteTree.js:22 TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by sesispla** [docarys/docarys#2]
Current implementation expects configuration to always include a "pages:" section.

If no "pages" section is specified, then there is an ugly error message:
```sh
docarys serve
Building documentation...
/Users/Sergio/Repositories/docarys/docarys/src/siteTree.js:22
            var key = Object.keys(pageCfg)[0];
                             ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at walk (/Users/Sergio/Repositories/docarys/docarys/src/siteTree.js:22:30)
    at buildSiteTree (/Users/Sergio/Repositories/docarys/docarys/src/siteTree.js:104:9)
    at SiteTree (/Users/Sergio/Repositories/docarys/docarys/src/siteTree.js:109:12)
    at Object.render (/Users/Sergio/Repositories/docarys/docarys/src/render.js:21:20)
    at Object.<anonymous> (/Users/Sergio/Repositories/docarys/docarys/src/docarys-serve.js:13:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

This is a known issue that should be fixed implementing a mechanism that auto creates a pages structure parting from the content in "docs" folder, the same way mkdocs does.

**Comment by sesispla** [comment]
The workaround for this is to always specify the pages structure in docarys.yml:

```yml
site_name: docarys - Statis Site Generator tool
theme: material
pages:
  Home: index.md
```
